/* soapCredentialBindingService.h
   Generated by gSOAP 2.8.66 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapCredentialBindingService_H
#define soapCredentialBindingService_H
#include "soapH.h"

    class SOAP_CMAC CredentialBindingService : public soap {
      public:
        /// Variables globally declared in onvif.h, if any
        /// Construct a service with new managing context
        CredentialBindingService();
        /// Copy constructor
        CredentialBindingService(const CredentialBindingService&);
        /// Construct service given a managing context
        CredentialBindingService(const struct soap&);
        /// Constructor taking input+output mode flags for the new managing context
        CredentialBindingService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        CredentialBindingService(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~CredentialBindingService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void CredentialBindingService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual CredentialBindingService *copy() SOAP_PURE_VIRTUAL_COPY;
        /// Copy assignment
        CredentialBindingService& operator=(const CredentialBindingService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns6__GetServiceCapabilities *ns6__GetServiceCapabilities, _ns6__GetServiceCapabilitiesResponse &ns6__GetServiceCapabilitiesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetSupportedFormatTypes' (returns SOAP_OK or error code)
        virtual int GetSupportedFormatTypes(_ns6__GetSupportedFormatTypes *ns6__GetSupportedFormatTypes, _ns6__GetSupportedFormatTypesResponse &ns6__GetSupportedFormatTypesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialInfo' (returns SOAP_OK or error code)
        virtual int GetCredentialInfo(_ns6__GetCredentialInfo *ns6__GetCredentialInfo, _ns6__GetCredentialInfoResponse &ns6__GetCredentialInfoResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialInfoList' (returns SOAP_OK or error code)
        virtual int GetCredentialInfoList(_ns6__GetCredentialInfoList *ns6__GetCredentialInfoList, _ns6__GetCredentialInfoListResponse &ns6__GetCredentialInfoListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentials' (returns SOAP_OK or error code)
        virtual int GetCredentials(_ns6__GetCredentials *ns6__GetCredentials, _ns6__GetCredentialsResponse &ns6__GetCredentialsResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialList' (returns SOAP_OK or error code)
        virtual int GetCredentialList(_ns6__GetCredentialList *ns6__GetCredentialList, _ns6__GetCredentialListResponse &ns6__GetCredentialListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'CreateCredential' (returns SOAP_OK or error code)
        virtual int CreateCredential(_ns6__CreateCredential *ns6__CreateCredential, _ns6__CreateCredentialResponse &ns6__CreateCredentialResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ModifyCredential' (returns SOAP_OK or error code)
        virtual int ModifyCredential(_ns6__ModifyCredential *ns6__ModifyCredential, _ns6__ModifyCredentialResponse &ns6__ModifyCredentialResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteCredential' (returns SOAP_OK or error code)
        virtual int DeleteCredential(_ns6__DeleteCredential *ns6__DeleteCredential, _ns6__DeleteCredentialResponse &ns6__DeleteCredentialResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialState' (returns SOAP_OK or error code)
        virtual int GetCredentialState(_ns6__GetCredentialState *ns6__GetCredentialState, _ns6__GetCredentialStateResponse &ns6__GetCredentialStateResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'EnableCredential' (returns SOAP_OK or error code)
        virtual int EnableCredential(_ns6__EnableCredential *ns6__EnableCredential, _ns6__EnableCredentialResponse &ns6__EnableCredentialResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DisableCredential' (returns SOAP_OK or error code)
        virtual int DisableCredential(_ns6__DisableCredential *ns6__DisableCredential, _ns6__DisableCredentialResponse &ns6__DisableCredentialResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ResetAntipassbackViolation' (returns SOAP_OK or error code)
        virtual int ResetAntipassbackViolation(_ns6__ResetAntipassbackViolation *ns6__ResetAntipassbackViolation, _ns6__ResetAntipassbackViolationResponse &ns6__ResetAntipassbackViolationResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialIdentifiers' (returns SOAP_OK or error code)
        virtual int GetCredentialIdentifiers(_ns6__GetCredentialIdentifiers *ns6__GetCredentialIdentifiers, _ns6__GetCredentialIdentifiersResponse &ns6__GetCredentialIdentifiersResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetCredentialIdentifier' (returns SOAP_OK or error code)
        virtual int SetCredentialIdentifier(_ns6__SetCredentialIdentifier *ns6__SetCredentialIdentifier, _ns6__SetCredentialIdentifierResponse &ns6__SetCredentialIdentifierResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteCredentialIdentifier' (returns SOAP_OK or error code)
        virtual int DeleteCredentialIdentifier(_ns6__DeleteCredentialIdentifier *ns6__DeleteCredentialIdentifier, _ns6__DeleteCredentialIdentifierResponse &ns6__DeleteCredentialIdentifierResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'GetCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int GetCredentialAccessProfiles(_ns6__GetCredentialAccessProfiles *ns6__GetCredentialAccessProfiles, _ns6__GetCredentialAccessProfilesResponse &ns6__GetCredentialAccessProfilesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'SetCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int SetCredentialAccessProfiles(_ns6__SetCredentialAccessProfiles *ns6__SetCredentialAccessProfiles, _ns6__SetCredentialAccessProfilesResponse &ns6__SetCredentialAccessProfilesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DeleteCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int DeleteCredentialAccessProfiles(_ns6__DeleteCredentialAccessProfiles *ns6__DeleteCredentialAccessProfiles, _ns6__DeleteCredentialAccessProfilesResponse &ns6__DeleteCredentialAccessProfilesResponse) SOAP_PURE_VIRTUAL;
    };
#endif
