/* soapPullPointSubscriptionBindingService.cpp
   Generated by gSOAP 2.8.66 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapPullPointSubscriptionBindingService.h"

PullPointSubscriptionBindingService::PullPointSubscriptionBindingService() : soap(SOAP_IO_DEFAULT)
{	PullPointSubscriptionBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PullPointSubscriptionBindingService::PullPointSubscriptionBindingService(const PullPointSubscriptionBindingService& rhs)
{	soap_copy_context(this, &rhs);
}

PullPointSubscriptionBindingService::PullPointSubscriptionBindingService(const struct soap &_soap) : soap(_soap)
{ }

PullPointSubscriptionBindingService::PullPointSubscriptionBindingService(soap_mode iomode) : soap(iomode)
{	PullPointSubscriptionBindingService_init(iomode, iomode);
}

PullPointSubscriptionBindingService::PullPointSubscriptionBindingService(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	PullPointSubscriptionBindingService_init(imode, omode);
}

PullPointSubscriptionBindingService::~PullPointSubscriptionBindingService()
{
	this->destroy();
}

void PullPointSubscriptionBindingService::PullPointSubscriptionBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL},
        {"saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
        {"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
        {"wsdd", "http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", NULL, NULL},
        {"ns12", "http://www.onvif.org/ver20/analytics", NULL, NULL},
        {"ns2", "http://www.onvif.org/ver10/pacs", NULL, NULL},
        {"ns10", "http://www.onvif.org/ver20/analytics/radiometry", NULL, NULL},
        {"xmime", "http://tempuri.org/xmime.xsd", NULL, NULL},
        {"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
        {"wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"tt", "http://www.onvif.org/ver10/schema", NULL, NULL},
        {"wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL},
        {"ns1", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL},
        {"ns11", "http://www.onvif.org/ver10/network/wsdl/", NULL, NULL},
        {"ns13", "http://www.onvif.org/ver10/schedule/wsdl", NULL, NULL},
        {"ns14", "http://www.onvif.org/ver10/thermal/wsdl", NULL, NULL},
        {"ns3", "http://www.onvif.org/ver10/accessrules/wsdl", NULL, NULL},
        {"ns4", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL},
        {"ns5", "http://www.onvif.org/ver10/advancedsecurity/wsdl", NULL, NULL},
        {"ns6", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
        {"ns7", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL},
        {"ns8", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
        {"ns9", "http://www.onvif.org/ver10/provisioning/wsdl", NULL, NULL},
        {"tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL},
        {"tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL},
        {"tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
        {"tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL},
        {"wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
        {"tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
        {"tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL},
        {"tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
        {"trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL},
        {"trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL},
        {"trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
        {"trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL},
        {"tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this, namespaces);
}

void PullPointSubscriptionBindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void PullPointSubscriptionBindingService::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	PullPointSubscriptionBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
PullPointSubscriptionBindingService *PullPointSubscriptionBindingService::copy()
{	PullPointSubscriptionBindingService *dup = SOAP_NEW_UNMANAGED(PullPointSubscriptionBindingService(*(struct soap*)this));
	return dup;
}
#endif

PullPointSubscriptionBindingService& PullPointSubscriptionBindingService::operator=(const PullPointSubscriptionBindingService& rhs)
{	soap_done(this);
	soap_copy_context(this, &rhs);
	return *this;
}

int PullPointSubscriptionBindingService::soap_close_socket()
{	return soap_closesock(this);
}

int PullPointSubscriptionBindingService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int PullPointSubscriptionBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int PullPointSubscriptionBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int PullPointSubscriptionBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int PullPointSubscriptionBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void PullPointSubscriptionBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void PullPointSubscriptionBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *PullPointSubscriptionBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void PullPointSubscriptionBindingService::soap_noheader()
{	this->header = NULL;
}

void PullPointSubscriptionBindingService::soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence)
{	::soap_header(this);
	this->header->wsse__Security = wsse__Security;
	this->header->wsa5__MessageID = wsa5__MessageID;
	this->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->header->wsa5__From = wsa5__From;
	this->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->header->wsa5__FaultTo = wsa5__FaultTo;
	this->header->wsa5__To = wsa5__To;
	this->header->wsa5__Action = wsa5__Action;
	this->header->chan__ChannelInstance = chan__ChannelInstance;
	this->header->wsdd__AppSequence = wsdd__AppSequence;
}

::SOAP_ENV__Header *PullPointSubscriptionBindingService::soap_header()
{	return this->header;
}

#ifndef WITH_NOIO
int PullPointSubscriptionBindingService::run(int port)
{	if (!soap_valid_socket(this->master) && !soap_valid_socket(this->bind(NULL, port, 100)))
		return this->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->errnum == 0) // timeout?
				this->error = SOAP_OK;
			break;
		}
		if (this->serve())
			break;
		this->destroy();
	}
	return this->error;
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int PullPointSubscriptionBindingService::ssl_run(int port)
{	if (!soap_valid_socket(this->master) && !soap_valid_socket(this->bind(NULL, port, 100)))
		return this->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->errnum == 0) // timeout?
				this->error = SOAP_OK;
			break;
		}
		if (this->ssl_accept() || this->serve())
			break;
		this->destroy();
	}
	return this->error;
}
#endif

SOAP_SOCKET PullPointSubscriptionBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET PullPointSubscriptionBindingService::accept()
{	return soap_accept(this);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int PullPointSubscriptionBindingService::ssl_accept()
{	return soap_ssl_accept(this);
}
#endif
#endif

int PullPointSubscriptionBindingService::serve()
{
#ifndef WITH_FASTCGI
	this->keep_alive = this->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (this->keep_alive > 0 && this->max_keep_alive > 0)
			this->keep_alive--;
#endif
		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if ((dispatch() || (this->fserveloop && this->fserveloop(this))) && this->error && this->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___tev__PullMessages(PullPointSubscriptionBindingService*);
static int serve___tev__Seek(PullPointSubscriptionBindingService*);
static int serve___tev__SetSynchronizationPoint(PullPointSubscriptionBindingService*);
static int serve___tev__GetServiceCapabilities(PullPointSubscriptionBindingService*);
static int serve___tev__CreatePullPointSubscription(PullPointSubscriptionBindingService*);
static int serve___tev__GetEventProperties(PullPointSubscriptionBindingService*);
static int serve___tev__Renew(PullPointSubscriptionBindingService*);
static int serve___tev__Unsubscribe(PullPointSubscriptionBindingService*);
static int serve___tev__Subscribe(PullPointSubscriptionBindingService*);
static int serve___tev__GetCurrentMessage(PullPointSubscriptionBindingService*);
static int serve___tev__Notify(PullPointSubscriptionBindingService*);
static int serve___tev__GetMessages(PullPointSubscriptionBindingService*);
static int serve___tev__DestroyPullPoint(PullPointSubscriptionBindingService*);
static int serve___tev__Notify_(PullPointSubscriptionBindingService*);
static int serve___tev__CreatePullPoint(PullPointSubscriptionBindingService*);
static int serve___tev__Renew_(PullPointSubscriptionBindingService*);
static int serve___tev__Unsubscribe_(PullPointSubscriptionBindingService*);
static int serve___tev__PauseSubscription(PullPointSubscriptionBindingService*);
static int serve___tev__ResumeSubscription(PullPointSubscriptionBindingService*);

int PullPointSubscriptionBindingService::dispatch()
{
	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "tev:PullMessages"))
		return serve___tev__PullMessages(this);
	if (!soap_match_tag(this, this->tag, "tev:Seek"))
		return serve___tev__Seek(this);
	if (!soap_match_tag(this, this->tag, "tev:SetSynchronizationPoint"))
		return serve___tev__SetSynchronizationPoint(this);
	if (!soap_match_tag(this, this->tag, "tev:GetServiceCapabilities"))
		return serve___tev__GetServiceCapabilities(this);
	if (!soap_match_tag(this, this->tag, "tev:CreatePullPointSubscription"))
		return serve___tev__CreatePullPointSubscription(this);
	if (!soap_match_tag(this, this->tag, "tev:GetEventProperties"))
		return serve___tev__GetEventProperties(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Renew"))
		return serve___tev__Renew(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Unsubscribe"))
		return serve___tev__Unsubscribe(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Subscribe"))
		return serve___tev__Subscribe(this);
	if (!soap_match_tag(this, this->tag, "wsnt:GetCurrentMessage"))
		return serve___tev__GetCurrentMessage(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Notify"))
		return serve___tev__Notify(this);
	if (!soap_match_tag(this, this->tag, "wsnt:GetMessages"))
		return serve___tev__GetMessages(this);
	if (!soap_match_tag(this, this->tag, "wsnt:DestroyPullPoint"))
		return serve___tev__DestroyPullPoint(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Notify"))
		return serve___tev__Notify_(this);
	if (!soap_match_tag(this, this->tag, "wsnt:CreatePullPoint"))
		return serve___tev__CreatePullPoint(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Renew"))
		return serve___tev__Renew_(this);
	if (!soap_match_tag(this, this->tag, "wsnt:Unsubscribe"))
		return serve___tev__Unsubscribe_(this);
	if (!soap_match_tag(this, this->tag, "wsnt:PauseSubscription"))
		return serve___tev__PauseSubscription(this);
	if (!soap_match_tag(this, this->tag, "wsnt:ResumeSubscription"))
		return serve___tev__ResumeSubscription(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve___tev__PullMessages(PullPointSubscriptionBindingService *soap)
{	struct __tev__PullMessages soap_tmp___tev__PullMessages;
	_tev__PullMessagesResponse tev__PullMessagesResponse;
	tev__PullMessagesResponse.soap_default(soap);
	soap_default___tev__PullMessages(soap, &soap_tmp___tev__PullMessages);
	if (!soap_get___tev__PullMessages(soap, &soap_tmp___tev__PullMessages, "-tev:PullMessages", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->PullMessages(soap_tmp___tev__PullMessages.tev__PullMessages, tev__PullMessagesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__PullMessagesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__PullMessagesResponse.soap_put(soap, "tev:PullMessagesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__PullMessagesResponse.soap_put(soap, "tev:PullMessagesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Seek(PullPointSubscriptionBindingService *soap)
{	struct __tev__Seek soap_tmp___tev__Seek;
	_tev__SeekResponse tev__SeekResponse;
	tev__SeekResponse.soap_default(soap);
	soap_default___tev__Seek(soap, &soap_tmp___tev__Seek);
	if (!soap_get___tev__Seek(soap, &soap_tmp___tev__Seek, "-tev:Seek", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Seek(soap_tmp___tev__Seek.tev__Seek, tev__SeekResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__SeekResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__SeekResponse.soap_put(soap, "tev:SeekResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__SeekResponse.soap_put(soap, "tev:SeekResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__SetSynchronizationPoint(PullPointSubscriptionBindingService *soap)
{	struct __tev__SetSynchronizationPoint soap_tmp___tev__SetSynchronizationPoint;
	_tev__SetSynchronizationPointResponse tev__SetSynchronizationPointResponse;
	tev__SetSynchronizationPointResponse.soap_default(soap);
	soap_default___tev__SetSynchronizationPoint(soap, &soap_tmp___tev__SetSynchronizationPoint);
	if (!soap_get___tev__SetSynchronizationPoint(soap, &soap_tmp___tev__SetSynchronizationPoint, "-tev:SetSynchronizationPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SetSynchronizationPoint(soap_tmp___tev__SetSynchronizationPoint.tev__SetSynchronizationPoint, tev__SetSynchronizationPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__SetSynchronizationPointResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__SetSynchronizationPointResponse.soap_put(soap, "tev:SetSynchronizationPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__SetSynchronizationPointResponse.soap_put(soap, "tev:SetSynchronizationPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__GetServiceCapabilities(PullPointSubscriptionBindingService *soap)
{	struct __tev__GetServiceCapabilities soap_tmp___tev__GetServiceCapabilities;
	_tev__GetServiceCapabilitiesResponse tev__GetServiceCapabilitiesResponse;
	tev__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___tev__GetServiceCapabilities(soap, &soap_tmp___tev__GetServiceCapabilities);
	if (!soap_get___tev__GetServiceCapabilities(soap, &soap_tmp___tev__GetServiceCapabilities, "-tev:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetServiceCapabilities(soap_tmp___tev__GetServiceCapabilities.tev__GetServiceCapabilities, tev__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__GetServiceCapabilitiesResponse.soap_put(soap, "tev:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__GetServiceCapabilitiesResponse.soap_put(soap, "tev:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__CreatePullPointSubscription(PullPointSubscriptionBindingService *soap)
{	struct __tev__CreatePullPointSubscription soap_tmp___tev__CreatePullPointSubscription;
	_tev__CreatePullPointSubscriptionResponse tev__CreatePullPointSubscriptionResponse;
	tev__CreatePullPointSubscriptionResponse.soap_default(soap);
	soap_default___tev__CreatePullPointSubscription(soap, &soap_tmp___tev__CreatePullPointSubscription);
	if (!soap_get___tev__CreatePullPointSubscription(soap, &soap_tmp___tev__CreatePullPointSubscription, "-tev:CreatePullPointSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CreatePullPointSubscription(soap_tmp___tev__CreatePullPointSubscription.tev__CreatePullPointSubscription, tev__CreatePullPointSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__CreatePullPointSubscriptionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__CreatePullPointSubscriptionResponse.soap_put(soap, "tev:CreatePullPointSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__CreatePullPointSubscriptionResponse.soap_put(soap, "tev:CreatePullPointSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__GetEventProperties(PullPointSubscriptionBindingService *soap)
{	struct __tev__GetEventProperties soap_tmp___tev__GetEventProperties;
	_tev__GetEventPropertiesResponse tev__GetEventPropertiesResponse;
	tev__GetEventPropertiesResponse.soap_default(soap);
	soap_default___tev__GetEventProperties(soap, &soap_tmp___tev__GetEventProperties);
	if (!soap_get___tev__GetEventProperties(soap, &soap_tmp___tev__GetEventProperties, "-tev:GetEventProperties", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetEventProperties(soap_tmp___tev__GetEventProperties.tev__GetEventProperties, tev__GetEventPropertiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	tev__GetEventPropertiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__GetEventPropertiesResponse.soap_put(soap, "tev:GetEventPropertiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__GetEventPropertiesResponse.soap_put(soap, "tev:GetEventPropertiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Renew(PullPointSubscriptionBindingService *soap)
{	struct __tev__Renew soap_tmp___tev__Renew;
	_wsnt__RenewResponse wsnt__RenewResponse;
	wsnt__RenewResponse.soap_default(soap);
	soap_default___tev__Renew(soap, &soap_tmp___tev__Renew);
	if (!soap_get___tev__Renew(soap, &soap_tmp___tev__Renew, "-tev:Renew", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Renew(soap_tmp___tev__Renew.wsnt__Renew, wsnt__RenewResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__RenewResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__RenewResponse.soap_put(soap, "wsnt:RenewResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__RenewResponse.soap_put(soap, "wsnt:RenewResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Unsubscribe(PullPointSubscriptionBindingService *soap)
{	struct __tev__Unsubscribe soap_tmp___tev__Unsubscribe;
	_wsnt__UnsubscribeResponse wsnt__UnsubscribeResponse;
	wsnt__UnsubscribeResponse.soap_default(soap);
	soap_default___tev__Unsubscribe(soap, &soap_tmp___tev__Unsubscribe);
	if (!soap_get___tev__Unsubscribe(soap, &soap_tmp___tev__Unsubscribe, "-tev:Unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Unsubscribe(soap_tmp___tev__Unsubscribe.wsnt__Unsubscribe, wsnt__UnsubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__UnsubscribeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__UnsubscribeResponse.soap_put(soap, "wsnt:UnsubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__UnsubscribeResponse.soap_put(soap, "wsnt:UnsubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Subscribe(PullPointSubscriptionBindingService *soap)
{	struct __tev__Subscribe soap_tmp___tev__Subscribe;
	_wsnt__SubscribeResponse wsnt__SubscribeResponse;
	wsnt__SubscribeResponse.soap_default(soap);
	soap_default___tev__Subscribe(soap, &soap_tmp___tev__Subscribe);
	if (!soap_get___tev__Subscribe(soap, &soap_tmp___tev__Subscribe, "-tev:Subscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Subscribe(soap_tmp___tev__Subscribe.wsnt__Subscribe, wsnt__SubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__SubscribeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__SubscribeResponse.soap_put(soap, "wsnt:SubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__SubscribeResponse.soap_put(soap, "wsnt:SubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__GetCurrentMessage(PullPointSubscriptionBindingService *soap)
{	struct __tev__GetCurrentMessage soap_tmp___tev__GetCurrentMessage;
	_wsnt__GetCurrentMessageResponse wsnt__GetCurrentMessageResponse;
	wsnt__GetCurrentMessageResponse.soap_default(soap);
	soap_default___tev__GetCurrentMessage(soap, &soap_tmp___tev__GetCurrentMessage);
	if (!soap_get___tev__GetCurrentMessage(soap, &soap_tmp___tev__GetCurrentMessage, "-tev:GetCurrentMessage", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetCurrentMessage(soap_tmp___tev__GetCurrentMessage.wsnt__GetCurrentMessage, wsnt__GetCurrentMessageResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__GetCurrentMessageResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__GetCurrentMessageResponse.soap_put(soap, "wsnt:GetCurrentMessageResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__GetCurrentMessageResponse.soap_put(soap, "wsnt:GetCurrentMessageResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Notify(PullPointSubscriptionBindingService *soap)
{	struct __tev__Notify soap_tmp___tev__Notify;
	soap_default___tev__Notify(soap, &soap_tmp___tev__Notify);
	if (!soap_get___tev__Notify(soap, &soap_tmp___tev__Notify, "-tev:Notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Notify(soap_tmp___tev__Notify.wsnt__Notify);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__GetMessages(PullPointSubscriptionBindingService *soap)
{	struct __tev__GetMessages soap_tmp___tev__GetMessages;
	_wsnt__GetMessagesResponse wsnt__GetMessagesResponse;
	wsnt__GetMessagesResponse.soap_default(soap);
	soap_default___tev__GetMessages(soap, &soap_tmp___tev__GetMessages);
	if (!soap_get___tev__GetMessages(soap, &soap_tmp___tev__GetMessages, "-tev:GetMessages", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetMessages(soap_tmp___tev__GetMessages.wsnt__GetMessages, wsnt__GetMessagesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__GetMessagesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__GetMessagesResponse.soap_put(soap, "wsnt:GetMessagesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__GetMessagesResponse.soap_put(soap, "wsnt:GetMessagesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__DestroyPullPoint(PullPointSubscriptionBindingService *soap)
{	struct __tev__DestroyPullPoint soap_tmp___tev__DestroyPullPoint;
	_wsnt__DestroyPullPointResponse wsnt__DestroyPullPointResponse;
	wsnt__DestroyPullPointResponse.soap_default(soap);
	soap_default___tev__DestroyPullPoint(soap, &soap_tmp___tev__DestroyPullPoint);
	if (!soap_get___tev__DestroyPullPoint(soap, &soap_tmp___tev__DestroyPullPoint, "-tev:DestroyPullPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->DestroyPullPoint(soap_tmp___tev__DestroyPullPoint.wsnt__DestroyPullPoint, wsnt__DestroyPullPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__DestroyPullPointResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__DestroyPullPointResponse.soap_put(soap, "wsnt:DestroyPullPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__DestroyPullPointResponse.soap_put(soap, "wsnt:DestroyPullPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Notify_(PullPointSubscriptionBindingService *soap)
{	struct __tev__Notify_ soap_tmp___tev__Notify_;
	soap_default___tev__Notify_(soap, &soap_tmp___tev__Notify_);
	if (!soap_get___tev__Notify_(soap, &soap_tmp___tev__Notify_, "-tev:Notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Notify_(soap_tmp___tev__Notify_.wsnt__Notify);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__CreatePullPoint(PullPointSubscriptionBindingService *soap)
{	struct __tev__CreatePullPoint soap_tmp___tev__CreatePullPoint;
	_wsnt__CreatePullPointResponse wsnt__CreatePullPointResponse;
	wsnt__CreatePullPointResponse.soap_default(soap);
	soap_default___tev__CreatePullPoint(soap, &soap_tmp___tev__CreatePullPoint);
	if (!soap_get___tev__CreatePullPoint(soap, &soap_tmp___tev__CreatePullPoint, "-tev:CreatePullPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CreatePullPoint(soap_tmp___tev__CreatePullPoint.wsnt__CreatePullPoint, wsnt__CreatePullPointResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__CreatePullPointResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__CreatePullPointResponse.soap_put(soap, "wsnt:CreatePullPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__CreatePullPointResponse.soap_put(soap, "wsnt:CreatePullPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Renew_(PullPointSubscriptionBindingService *soap)
{	struct __tev__Renew_ soap_tmp___tev__Renew_;
	_wsnt__RenewResponse wsnt__RenewResponse;
	wsnt__RenewResponse.soap_default(soap);
	soap_default___tev__Renew_(soap, &soap_tmp___tev__Renew_);
	if (!soap_get___tev__Renew_(soap, &soap_tmp___tev__Renew_, "-tev:Renew", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Renew_(soap_tmp___tev__Renew_.wsnt__Renew, wsnt__RenewResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__RenewResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__RenewResponse.soap_put(soap, "wsnt:RenewResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__RenewResponse.soap_put(soap, "wsnt:RenewResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__Unsubscribe_(PullPointSubscriptionBindingService *soap)
{	struct __tev__Unsubscribe_ soap_tmp___tev__Unsubscribe_;
	_wsnt__UnsubscribeResponse wsnt__UnsubscribeResponse;
	wsnt__UnsubscribeResponse.soap_default(soap);
	soap_default___tev__Unsubscribe_(soap, &soap_tmp___tev__Unsubscribe_);
	if (!soap_get___tev__Unsubscribe_(soap, &soap_tmp___tev__Unsubscribe_, "-tev:Unsubscribe", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Unsubscribe_(soap_tmp___tev__Unsubscribe_.wsnt__Unsubscribe, wsnt__UnsubscribeResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__UnsubscribeResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__UnsubscribeResponse.soap_put(soap, "wsnt:UnsubscribeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__UnsubscribeResponse.soap_put(soap, "wsnt:UnsubscribeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__PauseSubscription(PullPointSubscriptionBindingService *soap)
{	struct __tev__PauseSubscription soap_tmp___tev__PauseSubscription;
	_wsnt__PauseSubscriptionResponse wsnt__PauseSubscriptionResponse;
	wsnt__PauseSubscriptionResponse.soap_default(soap);
	soap_default___tev__PauseSubscription(soap, &soap_tmp___tev__PauseSubscription);
	if (!soap_get___tev__PauseSubscription(soap, &soap_tmp___tev__PauseSubscription, "-tev:PauseSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->PauseSubscription(soap_tmp___tev__PauseSubscription.wsnt__PauseSubscription, wsnt__PauseSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__PauseSubscriptionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__PauseSubscriptionResponse.soap_put(soap, "wsnt:PauseSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__PauseSubscriptionResponse.soap_put(soap, "wsnt:PauseSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___tev__ResumeSubscription(PullPointSubscriptionBindingService *soap)
{	struct __tev__ResumeSubscription soap_tmp___tev__ResumeSubscription;
	_wsnt__ResumeSubscriptionResponse wsnt__ResumeSubscriptionResponse;
	wsnt__ResumeSubscriptionResponse.soap_default(soap);
	soap_default___tev__ResumeSubscription(soap, &soap_tmp___tev__ResumeSubscription);
	if (!soap_get___tev__ResumeSubscription(soap, &soap_tmp___tev__ResumeSubscription, "-tev:ResumeSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->ResumeSubscription(soap_tmp___tev__ResumeSubscription.wsnt__ResumeSubscription, wsnt__ResumeSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	wsnt__ResumeSubscriptionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || wsnt__ResumeSubscriptionResponse.soap_put(soap, "wsnt:ResumeSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || wsnt__ResumeSubscriptionResponse.soap_put(soap, "wsnt:ResumeSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
