/* soapCredentialBindingProxy.h
   Generated by gSOAP 2.8.66 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapCredentialBindingProxy_H
#define soapCredentialBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC CredentialBindingProxy : public soap {
      public:
        /// Endpoint URL of service 'CredentialBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        CredentialBindingProxy();
        /// Copy constructor
        CredentialBindingProxy(const CredentialBindingProxy& rhs);
        /// Construct proxy given a managing context
        CredentialBindingProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        CredentialBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        CredentialBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        CredentialBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        CredentialBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~CredentialBindingProxy();
        /// Initializer used by constructors
        virtual void CredentialBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual CredentialBindingProxy *copy();
        /// Copy assignment
        CredentialBindingProxy& operator=(const CredentialBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns6__GetServiceCapabilities *ns6__GetServiceCapabilities, _ns6__GetServiceCapabilitiesResponse &ns6__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns6__GetServiceCapabilities, ns6__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns6__GetServiceCapabilities *ns6__GetServiceCapabilities, _ns6__GetServiceCapabilitiesResponse &ns6__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetSupportedFormatTypes' (returns SOAP_OK or error code)
        virtual int GetSupportedFormatTypes(_ns6__GetSupportedFormatTypes *ns6__GetSupportedFormatTypes, _ns6__GetSupportedFormatTypesResponse &ns6__GetSupportedFormatTypesResponse)
        { return this->GetSupportedFormatTypes(NULL, NULL, ns6__GetSupportedFormatTypes, ns6__GetSupportedFormatTypesResponse); }
        virtual int GetSupportedFormatTypes(const char *soap_endpoint, const char *soap_action, _ns6__GetSupportedFormatTypes *ns6__GetSupportedFormatTypes, _ns6__GetSupportedFormatTypesResponse &ns6__GetSupportedFormatTypesResponse);
        /// Web service operation 'GetCredentialInfo' (returns SOAP_OK or error code)
        virtual int GetCredentialInfo(_ns6__GetCredentialInfo *ns6__GetCredentialInfo, _ns6__GetCredentialInfoResponse &ns6__GetCredentialInfoResponse)
        { return this->GetCredentialInfo(NULL, NULL, ns6__GetCredentialInfo, ns6__GetCredentialInfoResponse); }
        virtual int GetCredentialInfo(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialInfo *ns6__GetCredentialInfo, _ns6__GetCredentialInfoResponse &ns6__GetCredentialInfoResponse);
        /// Web service operation 'GetCredentialInfoList' (returns SOAP_OK or error code)
        virtual int GetCredentialInfoList(_ns6__GetCredentialInfoList *ns6__GetCredentialInfoList, _ns6__GetCredentialInfoListResponse &ns6__GetCredentialInfoListResponse)
        { return this->GetCredentialInfoList(NULL, NULL, ns6__GetCredentialInfoList, ns6__GetCredentialInfoListResponse); }
        virtual int GetCredentialInfoList(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialInfoList *ns6__GetCredentialInfoList, _ns6__GetCredentialInfoListResponse &ns6__GetCredentialInfoListResponse);
        /// Web service operation 'GetCredentials' (returns SOAP_OK or error code)
        virtual int GetCredentials(_ns6__GetCredentials *ns6__GetCredentials, _ns6__GetCredentialsResponse &ns6__GetCredentialsResponse)
        { return this->GetCredentials(NULL, NULL, ns6__GetCredentials, ns6__GetCredentialsResponse); }
        virtual int GetCredentials(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentials *ns6__GetCredentials, _ns6__GetCredentialsResponse &ns6__GetCredentialsResponse);
        /// Web service operation 'GetCredentialList' (returns SOAP_OK or error code)
        virtual int GetCredentialList(_ns6__GetCredentialList *ns6__GetCredentialList, _ns6__GetCredentialListResponse &ns6__GetCredentialListResponse)
        { return this->GetCredentialList(NULL, NULL, ns6__GetCredentialList, ns6__GetCredentialListResponse); }
        virtual int GetCredentialList(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialList *ns6__GetCredentialList, _ns6__GetCredentialListResponse &ns6__GetCredentialListResponse);
        /// Web service operation 'CreateCredential' (returns SOAP_OK or error code)
        virtual int CreateCredential(_ns6__CreateCredential *ns6__CreateCredential, _ns6__CreateCredentialResponse &ns6__CreateCredentialResponse)
        { return this->CreateCredential(NULL, NULL, ns6__CreateCredential, ns6__CreateCredentialResponse); }
        virtual int CreateCredential(const char *soap_endpoint, const char *soap_action, _ns6__CreateCredential *ns6__CreateCredential, _ns6__CreateCredentialResponse &ns6__CreateCredentialResponse);
        /// Web service operation 'ModifyCredential' (returns SOAP_OK or error code)
        virtual int ModifyCredential(_ns6__ModifyCredential *ns6__ModifyCredential, _ns6__ModifyCredentialResponse &ns6__ModifyCredentialResponse)
        { return this->ModifyCredential(NULL, NULL, ns6__ModifyCredential, ns6__ModifyCredentialResponse); }
        virtual int ModifyCredential(const char *soap_endpoint, const char *soap_action, _ns6__ModifyCredential *ns6__ModifyCredential, _ns6__ModifyCredentialResponse &ns6__ModifyCredentialResponse);
        /// Web service operation 'DeleteCredential' (returns SOAP_OK or error code)
        virtual int DeleteCredential(_ns6__DeleteCredential *ns6__DeleteCredential, _ns6__DeleteCredentialResponse &ns6__DeleteCredentialResponse)
        { return this->DeleteCredential(NULL, NULL, ns6__DeleteCredential, ns6__DeleteCredentialResponse); }
        virtual int DeleteCredential(const char *soap_endpoint, const char *soap_action, _ns6__DeleteCredential *ns6__DeleteCredential, _ns6__DeleteCredentialResponse &ns6__DeleteCredentialResponse);
        /// Web service operation 'GetCredentialState' (returns SOAP_OK or error code)
        virtual int GetCredentialState(_ns6__GetCredentialState *ns6__GetCredentialState, _ns6__GetCredentialStateResponse &ns6__GetCredentialStateResponse)
        { return this->GetCredentialState(NULL, NULL, ns6__GetCredentialState, ns6__GetCredentialStateResponse); }
        virtual int GetCredentialState(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialState *ns6__GetCredentialState, _ns6__GetCredentialStateResponse &ns6__GetCredentialStateResponse);
        /// Web service operation 'EnableCredential' (returns SOAP_OK or error code)
        virtual int EnableCredential(_ns6__EnableCredential *ns6__EnableCredential, _ns6__EnableCredentialResponse &ns6__EnableCredentialResponse)
        { return this->EnableCredential(NULL, NULL, ns6__EnableCredential, ns6__EnableCredentialResponse); }
        virtual int EnableCredential(const char *soap_endpoint, const char *soap_action, _ns6__EnableCredential *ns6__EnableCredential, _ns6__EnableCredentialResponse &ns6__EnableCredentialResponse);
        /// Web service operation 'DisableCredential' (returns SOAP_OK or error code)
        virtual int DisableCredential(_ns6__DisableCredential *ns6__DisableCredential, _ns6__DisableCredentialResponse &ns6__DisableCredentialResponse)
        { return this->DisableCredential(NULL, NULL, ns6__DisableCredential, ns6__DisableCredentialResponse); }
        virtual int DisableCredential(const char *soap_endpoint, const char *soap_action, _ns6__DisableCredential *ns6__DisableCredential, _ns6__DisableCredentialResponse &ns6__DisableCredentialResponse);
        /// Web service operation 'ResetAntipassbackViolation' (returns SOAP_OK or error code)
        virtual int ResetAntipassbackViolation(_ns6__ResetAntipassbackViolation *ns6__ResetAntipassbackViolation, _ns6__ResetAntipassbackViolationResponse &ns6__ResetAntipassbackViolationResponse)
        { return this->ResetAntipassbackViolation(NULL, NULL, ns6__ResetAntipassbackViolation, ns6__ResetAntipassbackViolationResponse); }
        virtual int ResetAntipassbackViolation(const char *soap_endpoint, const char *soap_action, _ns6__ResetAntipassbackViolation *ns6__ResetAntipassbackViolation, _ns6__ResetAntipassbackViolationResponse &ns6__ResetAntipassbackViolationResponse);
        /// Web service operation 'GetCredentialIdentifiers' (returns SOAP_OK or error code)
        virtual int GetCredentialIdentifiers(_ns6__GetCredentialIdentifiers *ns6__GetCredentialIdentifiers, _ns6__GetCredentialIdentifiersResponse &ns6__GetCredentialIdentifiersResponse)
        { return this->GetCredentialIdentifiers(NULL, NULL, ns6__GetCredentialIdentifiers, ns6__GetCredentialIdentifiersResponse); }
        virtual int GetCredentialIdentifiers(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialIdentifiers *ns6__GetCredentialIdentifiers, _ns6__GetCredentialIdentifiersResponse &ns6__GetCredentialIdentifiersResponse);
        /// Web service operation 'SetCredentialIdentifier' (returns SOAP_OK or error code)
        virtual int SetCredentialIdentifier(_ns6__SetCredentialIdentifier *ns6__SetCredentialIdentifier, _ns6__SetCredentialIdentifierResponse &ns6__SetCredentialIdentifierResponse)
        { return this->SetCredentialIdentifier(NULL, NULL, ns6__SetCredentialIdentifier, ns6__SetCredentialIdentifierResponse); }
        virtual int SetCredentialIdentifier(const char *soap_endpoint, const char *soap_action, _ns6__SetCredentialIdentifier *ns6__SetCredentialIdentifier, _ns6__SetCredentialIdentifierResponse &ns6__SetCredentialIdentifierResponse);
        /// Web service operation 'DeleteCredentialIdentifier' (returns SOAP_OK or error code)
        virtual int DeleteCredentialIdentifier(_ns6__DeleteCredentialIdentifier *ns6__DeleteCredentialIdentifier, _ns6__DeleteCredentialIdentifierResponse &ns6__DeleteCredentialIdentifierResponse)
        { return this->DeleteCredentialIdentifier(NULL, NULL, ns6__DeleteCredentialIdentifier, ns6__DeleteCredentialIdentifierResponse); }
        virtual int DeleteCredentialIdentifier(const char *soap_endpoint, const char *soap_action, _ns6__DeleteCredentialIdentifier *ns6__DeleteCredentialIdentifier, _ns6__DeleteCredentialIdentifierResponse &ns6__DeleteCredentialIdentifierResponse);
        /// Web service operation 'GetCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int GetCredentialAccessProfiles(_ns6__GetCredentialAccessProfiles *ns6__GetCredentialAccessProfiles, _ns6__GetCredentialAccessProfilesResponse &ns6__GetCredentialAccessProfilesResponse)
        { return this->GetCredentialAccessProfiles(NULL, NULL, ns6__GetCredentialAccessProfiles, ns6__GetCredentialAccessProfilesResponse); }
        virtual int GetCredentialAccessProfiles(const char *soap_endpoint, const char *soap_action, _ns6__GetCredentialAccessProfiles *ns6__GetCredentialAccessProfiles, _ns6__GetCredentialAccessProfilesResponse &ns6__GetCredentialAccessProfilesResponse);
        /// Web service operation 'SetCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int SetCredentialAccessProfiles(_ns6__SetCredentialAccessProfiles *ns6__SetCredentialAccessProfiles, _ns6__SetCredentialAccessProfilesResponse &ns6__SetCredentialAccessProfilesResponse)
        { return this->SetCredentialAccessProfiles(NULL, NULL, ns6__SetCredentialAccessProfiles, ns6__SetCredentialAccessProfilesResponse); }
        virtual int SetCredentialAccessProfiles(const char *soap_endpoint, const char *soap_action, _ns6__SetCredentialAccessProfiles *ns6__SetCredentialAccessProfiles, _ns6__SetCredentialAccessProfilesResponse &ns6__SetCredentialAccessProfilesResponse);
        /// Web service operation 'DeleteCredentialAccessProfiles' (returns SOAP_OK or error code)
        virtual int DeleteCredentialAccessProfiles(_ns6__DeleteCredentialAccessProfiles *ns6__DeleteCredentialAccessProfiles, _ns6__DeleteCredentialAccessProfilesResponse &ns6__DeleteCredentialAccessProfilesResponse)
        { return this->DeleteCredentialAccessProfiles(NULL, NULL, ns6__DeleteCredentialAccessProfiles, ns6__DeleteCredentialAccessProfilesResponse); }
        virtual int DeleteCredentialAccessProfiles(const char *soap_endpoint, const char *soap_action, _ns6__DeleteCredentialAccessProfiles *ns6__DeleteCredentialAccessProfiles, _ns6__DeleteCredentialAccessProfilesResponse &ns6__DeleteCredentialAccessProfilesResponse);
    };
#endif
